# -*- coding: utf-8 -*-
"""Neural Net Using FrameWork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14iQ41AZVfHXutZGIB1dJci-VgxsULzWl

# Neural Network(MLP,CNN) Implementation using Keras

* This notebook is the extension of [Neural Net from Scratch](https://colab.research.google.com/drive/1Dn1QJ2sIGOEZ4O6Fy5xAtZsRngtgmn9e)
 * This notebook will implement Neural Net(**MLP,CNN**) using tensorflow keras framework

## Packages
"""

import keras
import random
import pandas as pd
import numpy as np
import seaborn as sns
import tensorflow as tf
import matplotlib.pyplot as plt
from keras.models import Model
from keras.applications import MobileNetV2
from keras import layers,datasets,optimizers,regularizers,models
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.initializers import random_uniform, glorot_uniform, constant, identity

physical_devices = tf.config.list_physical_devices()

if physical_devices:
    print("Available physical devices:")
    for device in physical_devices:
        print(f"- {device.name} ({device.device_type})")
else:
    print("No physical devices available (TensorFlow not initialized or no devices found).")

"""## Helper function

### ProgressBar CallBack
"""

class CustomProgbarLogger(keras.callbacks.Callback):
    def __init__(self, print_every=100):
        super().__init__()
        self.print_every = print_every

    def on_epoch_end(self, epoch, logs=None):
        if logs is None:
            return  # safety check

        total_epochs = self.params['epochs']
        epoch_display = epoch + 1  # convert 0-based -> 1-based

        # Print on 1st epoch, every `print_every`, and the final epoch
        if (epoch_display == 1 or
            epoch_display % self.print_every == 0 or
            epoch_display == total_epochs):

            print(
                f"Epoch {epoch_display}/{total_epochs} - "
                f"loss: {logs.get('loss', float('nan')):.4f} - "
                f"accuracy: {logs.get('accuracy', float('nan')):.4f} | "
                f"val_loss: {logs.get('val_loss', float('nan')):.4f} - "
                f"val_accuracy: {logs.get('val_accuracy', float('nan')):.4f}"
            )

"""### Early Stop Callback"""

EarlyStopping = keras.callbacks.EarlyStopping(
    monitor='val_loss',
    patience=500,
    restore_best_weights=True
)

"""### Reduce Learning Rate"""

ReduceLR = keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=500,
    min_lr=1e-6,
    verbose=1
)

"""### DataAugmentor"""

datagen = ImageDataGenerator(
    rotation_range=10,              # randomly rotate images by up to 10 degrees
    width_shift_range=0.1,          # randomly shift images horizontally by 10% of width
    height_shift_range=0.1,         # randomly shift images vertically by 10% of height
    horizontal_flip=True,           # randomly flip images horizontally
    zoom_range=0.1,                 # random zoom
    brightness_range=[0.8, 1.2],    # random brightness adjustment
    channel_shift_range=20.0,       # random RGB channel shifts
    shear_range=0.1,                # shear transformation
    fill_mode='nearest',
    rescale=1./255
)

"""## Data Loading and Preprocessing

### Load Dataset
"""

(x_train, y_train), (x_test, y_test) = datasets.cifar10.load_data()

print(f"Original CIFAR-10 train shapes: x={x_train.shape}, y={y_train.shape}")
print(f"Original CIFAR-10 test shapes: x={x_test.shape}, y={y_test.shape}")

"""### Data preprocssing"""

# For example, let's choose 'cat' (label 3) and 'dog' (label 5)
class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']
class_1_label = 3 # cat
class_2_label = 5 # dog

# Select images and labels belonging to the chosen classes
train_filter = np.where((y_train == class_1_label) | (y_train == class_2_label))[0]
test_filter = np.where((y_test == class_1_label) | (y_test == class_2_label))[0]

x_train, y_train = x_train[train_filter], y_train[train_filter]
x_test, y_test = x_test[test_filter], y_test[test_filter]

# Convert labels to binary (0 for class_1, 1 for class_2)
y_train = np.where(y_train == class_1_label, 0, 1)
y_test = np.where(y_test == class_1_label, 0, 1)

# Normalize the pixel values to be between 0 and 1
# x_train = x_train / 255.0
# x_test = x_test / 255.0

# Suppose x_test and y_test are tf.Tensors
x_test_np = x_test.numpy() if tf.is_tensor(x_test) else x_test
y_test_np = y_test.numpy() if tf.is_tensor(y_test) else y_test

# Split into Test into validation (50%) and test (50%)
x_val, x_test, y_val, y_test = train_test_split(
    x_test_np, y_test_np,
    test_size=0.5,          # 50% goes to final test
    stratify=y_test_np,        # preserve class balance
    random_state=42         # reproducibility
)

# Print shapes to see the size of the binary dataset
print(f"\nBinary train shapes (cat vs dog): x={x_train.shape}, y={y_train.shape}")
print(f"Binary validation shapes (cat vs dog): x={x_val.shape}, y={y_val.shape}")
print(f"Binary test shapes (cat vs dog): x={x_test.shape}, y={y_test.shape}")

# Pick one sample image from training data
img = x_train[0]  # You can change the index to view another image
img_array = img.reshape((1,) + img.shape)

# Plot original image
plt.figure(figsize=(5, 5))
plt.subplot(3, 3, 1)
plt.imshow(img.astype("uint8"))
plt.title("Original")
plt.axis("off")

# Generate and plot augmentations
i = 0
for batch in datagen.flow(img_array, batch_size=1):
    plt.subplot(3, 3, i + 2)
    plt.imshow(tf.cast(batch[0] / 255.0, tf.float32))
    plt.title(f"Aug {i+1}")
    plt.axis("off")
    i += 1
    if i == 8:  # show 8 augmentations
        break

plt.tight_layout()
plt.show()

# Optional: Display a few images from the binary dataset
plt.figure(figsize=(8,8))
for k in range(5):
    plt.subplot(1, 5, k + 1)
    i = random.randrange(len(x_train))
    plt.imshow(x_train[i])
    plt.title(f"Label: {y_train[i]} ({class_names[class_1_label] if y_train[i] == 0 else class_names[class_2_label]})")
    plt.axis('off')
plt.tight_layout()
plt.show()

"""## Model Training and Testing

### Basic MLP Model

#### Network Architecture
"""

def mlp_classifier():
    model = tf.keras.Sequential([
        tf.keras.Input(shape=(32, 32, 3)),  # Input layer
        layers.Flatten(),  # Flatten the 32x32 pixel images
        layers.Dense(64, activation='relu'),
        layers.Dense(32, activation='relu'),
        layers.Dense(16, activation='tanh'),
        layers.Dense(1, activation='sigmoid') # Output layer for binary classification
    ])
    return model

mlp_model = mlp_classifier()
optimizer = optimizers.SGD(learning_rate=0.1)
mlp_model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
mlp_model.summary()

"""#### Model Training"""

epochs, batch_size = 20000, len(x_train)
total_print = 25
mlp_model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size, callbacks=[CustomProgbarLogger(print_every=epochs // total_print)], verbose=0)

"""#### Model Evaluation"""

mlp_model.evaluate(x_test, y_test)

y_pred = mlp_model.predict(x_test)
y_pred_classes = (y_pred > 0.5).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred_classes)

# Define the class names for the binary classification
binary_class_names = [class_names[class_1_label], class_names[class_2_label]]

# Create a heatmap
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=binary_class_names, yticklabels=binary_class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

"""### MLP with Batch Normalization

#### Network Architecture
"""

def mlp_bn_classifier():
    model = tf.keras.Sequential([
        tf.keras.Input(shape=(32, 32, 3)),  # Input layer
        layers.Flatten(),  # Flatten the 32x32 pixel images
        layers.Dense(64, activation='relu'),
        layers.BatchNormalization(),
        layers.Dropout(0.2),
        layers.Dense(32, activation='relu'),
        layers.BatchNormalization(),\
        layers.Dropout(0.2),
        layers.Dense(16, activation='relu'),
        layers.Dropout(0.2),
        layers.Dense(1, activation='sigmoid') # Output layer for binary classification
    ])
    return model

"""#### Model Training"""

mlp_bn_model = mlp_bn_classifier()
optimizer = optimizers.SGD(learning_rate=0.1)
mlp_bn_model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])
mlp_bn_model.summary()

epochs, batch_size = 20000, len(x_train)
total_print = 25
mlp_bn_model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size, callbacks=[CustomProgbarLogger(print_every=epochs // total_print)], verbose=0)

"""#### Model Evaluation"""

mlp_bn_model.evaluate(x_test, y_test)

y_pred = mlp_bn_model.predict(x_test)
y_pred_classes = (y_pred > 0.5).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred_classes)

# Define the class names for the binary classification
binary_class_names = [class_names[class_1_label], class_names[class_2_label]]

# Create a heatmap
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=binary_class_names, yticklabels=binary_class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

"""### Basic CNN Model

#### Network Architecture
"""

def cnn_classifier():
    model = tf.keras.Sequential([
        tf.keras.Input(shape=(32, 32, 3)),  # Input layer
        layers.ZeroPadding2D(padding=(2, 2)),
        layers.Conv2D(filters=32, kernel_size=(7,7), strides=(1,1), name='conv0'),
        layers.BatchNormalization(axis=3, name='bn0'),
        layers.ReLU(name='relu'),
        layers.MaxPooling2D(),
        layers.Flatten(),
        layers.Dense(1, activation='sigmoid') # Output layer for binary classification
    ])
    return model

"""#### Model Training"""

cnn_model = cnn_classifier()
#optimizer = optimizers.SGD(learning_rate=0.1)
cnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
cnn_model.summary()

epochs, batch_size = 5000, len(x_train)
total_print = 25
history = cnn_model.fit(x_train, y_train,
              epochs=epochs,
              batch_size=batch_size,
              validation_data=(x_val, y_val),
              callbacks=[CustomProgbarLogger(print_every=epochs//total_print),EarlyStopping],
              verbose=0)

"""#### Model Evaluation"""

cnn_model.evaluate(x_test, y_test)

# The history.history["loss"] entry is a dictionary with as many values as epochs that the
# model was trained on.
df_loss_acc = pd.DataFrame(history.history)
df_loss= df_loss_acc[['loss','val_loss']]
df_loss.rename(columns={'loss':'train','val_loss':'validation'})
df_acc= df_loss_acc[['accuracy','val_accuracy']]
df_acc.rename(columns={'accuracy':'train','val_accuracy':'validation'})
df_loss.plot(title='Model loss',figsize=(12,5)).set(xlabel='Epoch',ylabel='Loss')
df_acc.plot(title='Model Accuracy',figsize=(12,5)).set(xlabel='Epoch',ylabel='Accuracy')

y_pred = cnn_model.predict(x_test)
y_pred_classes = (y_pred > 0.5).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred_classes)

# Define the class names for the binary classification
binary_class_names = [class_names[class_1_label], class_names[class_2_label]]

# Create a heatmap
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=binary_class_names, yticklabels=binary_class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

"""### CNN With BN and Dropout

#### Network Architecture
"""

def cnn_lenet5_classifier():
    model = tf.keras.Sequential([
        tf.keras.Input(shape=(32, 32, 3)),  # Input layer
        layers.Conv2D(filters=6, kernel_size=(5,5), strides=(1,1), use_bias=False, name='conv1'),
        layers.BatchNormalization(),
        layers.Activation('tanh'),
        layers.MaxPooling2D(pool_size=(2,2), strides=2, name='pool1'),
        layers.Dropout(0.25),

        layers.Conv2D(filters=16, kernel_size=(5,5), strides=(1,1), use_bias=False, name='conv2'),
        layers.BatchNormalization(),
        layers.Activation('tanh'),
        layers.MaxPooling2D(pool_size=(2,2), strides=2, name='pool2'),
        layers.Dropout(0.25),

        layers.Flatten(name='flat1'),

        layers.Dense(64, use_bias=False),
        layers.BatchNormalization(),
        layers.Activation('tanh'),
        layers.Dropout(0.5),

        layers.Dense(16, use_bias=False),
        layers.BatchNormalization(),
        layers.Activation('tanh'),
        layers.Dropout(0.5),

        layers.Dense(1, activation='sigmoid', name='output') # Output layer for binary classification
    ])
    return model

"""#### Model Training"""

cnn_lenet5_model = cnn_lenet5_classifier()
#optimizer = optimizers.SGD(learning_rate=0.1)
cnn_lenet5_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
cnn_lenet5_model.summary()

epochs, batch_size = 2000, len(x_train)
total_print = 25
history = cnn_lenet5_model.fit(x_train, y_train,
                               epochs=epochs,
                               batch_size=batch_size,
                               validation_data=(x_val, y_val),
                               callbacks=[CustomProgbarLogger(print_every=epochs//total_print),
                                          EarlyStopping,
                                          ReduceLR],
                               verbose=0)

"""#### Model Evaluation"""

cnn_lenet5_model.evaluate(x_test, y_test)

# The history.history["loss"] entry is a dictionary with as many values as epochs that the
# model was trained on.
df_loss_acc = pd.DataFrame(history.history)
df_loss= df_loss_acc[['loss','val_loss']]
df_loss.rename(columns={'loss':'train','val_loss':'validation'})
df_acc= df_loss_acc[['accuracy','val_accuracy']]
df_acc.rename(columns={'accuracy':'train','val_accuracy':'validation'})
df_loss.plot(title='Model loss',figsize=(12,5)).set(xlabel='Epoch',ylabel='Loss')
df_acc.plot(title='Model Accuracy',figsize=(12,5)).set(xlabel='Epoch',ylabel='Accuracy')

y_pred = cnn_lenet5_model.predict(x_test)
y_pred_classes = (y_pred > 0.5).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred_classes)

# Define the class names for the binary classification
binary_class_names = [class_names[class_1_label], class_names[class_2_label]]

# Create a heatmap
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=binary_class_names, yticklabels=binary_class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

"""### CNN with Data Augmentation

#### Network Architecture
"""

def cnn_with_data_aug_classifier():
    model = tf.keras.Sequential([
        tf.keras.Input(shape=(32, 32, 3)),  # Input layer
        layers.Conv2D(filters=6, kernel_size=(5,5), strides=(1,1), use_bias=False, name='conv1'),
        layers.BatchNormalization(),
        layers.Activation('tanh'),
        layers.MaxPooling2D(pool_size=(2,2), strides=2, name='pool1'),
        # layers.Dropout(0.25),

        layers.Conv2D(filters=16, kernel_size=(5,5), strides=(1,1), use_bias=False, name='conv2'),
        layers.BatchNormalization(),
        layers.Activation('tanh'),
        layers.MaxPooling2D(pool_size=(2,2), strides=2, name='pool2'),
        # layers.Dropout(0.25),

        layers.Flatten(name='flat1'),

        layers.Dense(64, use_bias=False),
        layers.BatchNormalization(),
        layers.Activation('tanh'),
        # layers.Dropout(0.5),

        layers.Dense(16, use_bias=False),
        layers.BatchNormalization(),
        layers.Activation('tanh'),
        # layers.Dropout(0.5),

        layers.Dense(1, activation='sigmoid', name='output') # Output layer for binary classification
    ])
    return model

"""#### Model Training"""

cnn_with_data_aug_model = cnn_with_data_aug_classifier()
#optimizer = optimizers.SGD(learning_rate=0.1)
cnn_with_data_aug_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
cnn_with_data_aug_model.summary()

epochs, batch_size = 1000, len(x_train)
total_print = 25
history = cnn_with_data_aug_model.fit(
                               datagen.flow(x_train, y_train, batch_size=batch_size),
                               epochs=epochs,
                              #  batch_size=batch_size,
                               validation_data=(x_val, y_val),
                               callbacks=[CustomProgbarLogger(print_every=epochs//total_print),
                                          EarlyStopping,
                                          ReduceLR],
                               verbose=0)

"""#### Model Evaluation"""

cnn_with_data_aug_model.evaluate(x_test, y_test)

# The history.history["loss"] entry is a dictionary with as many values as epochs that the
# model was trained on.
df_loss_acc = pd.DataFrame(history.history)
df_loss= df_loss_acc[['loss','val_loss']]
df_loss.rename(columns={'loss':'train','val_loss':'validation'})
df_acc= df_loss_acc[['accuracy','val_accuracy']]
df_acc.rename(columns={'accuracy':'train','val_accuracy':'validation'})
df_loss.plot(title='Model loss',figsize=(12,5)).set(xlabel='Epoch',ylabel='Loss')
df_acc.plot(title='Model Accuracy',figsize=(12,5)).set(xlabel='Epoch',ylabel='Accuracy')

y_pred = cnn_with_data_aug_model.predict(x_test)
y_pred_classes = (y_pred > 0.5).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred_classes)

# Define the class names for the binary classification
binary_class_names = [class_names[class_1_label], class_names[class_2_label]]

# Create a heatmap
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=binary_class_names, yticklabels=binary_class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

"""### Larger CNN with Data Augmentation

#### Network Architecture
"""

def large_cnn_with_data_aug_classifier():
    model = tf.keras.Sequential([
        tf.keras.Input(shape=(32, 32, 3)),
        layers.Conv2D(32, (3,3), padding='same', name='conv1'),
        layers.BatchNormalization(),
        layers.Activation('relu'),

        layers.Conv2D(32, (3,3), padding='same', name='conv2'),
        layers.BatchNormalization(),
        layers.Activation('relu'),
        layers.MaxPooling2D((2,2), strides=2),
        # layers.Dropout(0.25),

        layers.Conv2D(64, (3,3), padding='same', name='conv3'),
        layers.BatchNormalization(),
        layers.Activation('relu'),

        layers.Conv2D(64, (3,3), padding='same', name='conv4'),
        layers.BatchNormalization(),
        layers.Activation('relu'),
        layers.MaxPooling2D((2,2), strides=2),
        # layers.Dropout(0.25),

        layers.Conv2D(128, (3,3), padding='same', name='conv5'),
        layers.BatchNormalization(),
        layers.Activation('relu'),
        layers.MaxPooling2D((2,2), strides=2),
        # layers.Dropout(0.25),

        layers.Flatten(),
        layers.Dense(128),
        layers.BatchNormalization(),
        layers.Activation('relu'),
        # layers.Dropout(0.5),

        layers.Dense(1, activation='sigmoid')
    ])
    return model

"""#### Model Training"""

large_cnn_with_data_aug_model = large_cnn_with_data_aug_classifier()
#optimizer = optimizers.SGD(learning_rate=0.1)
large_cnn_with_data_aug_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
large_cnn_with_data_aug_model.summary()

epochs, batch_size = 1000, len(x_train)
total_print = 25
history = large_cnn_with_data_aug_model.fit(
                               datagen.flow(x_train, y_train, batch_size=batch_size),
                               epochs=epochs,
                              #  batch_size=batch_size,
                               validation_data=(x_val, y_val),
                               callbacks=[CustomProgbarLogger(print_every=epochs//total_print),
                                          EarlyStopping,
                                          ReduceLR],
                               verbose=0)

"""#### Model Evaluation"""

large_cnn_with_data_aug_model.save('large_cnn_with_data_aug_model_weight.keras')
large_cnn_with_data_aug_model.evaluate(x_test, y_test)

# The history.history["loss"] entry is a dictionary with as many values as epochs that the
# model was trained on.
df_loss_acc = pd.DataFrame(history.history)
df_loss= df_loss_acc[['loss','val_loss']]
df_loss.rename(columns={'loss':'train','val_loss':'validation'})
df_acc= df_loss_acc[['accuracy','val_accuracy']]
df_acc.rename(columns={'accuracy':'train','val_accuracy':'validation'})
df_loss.plot(title='Model loss',figsize=(12,5)).set(xlabel='Epoch',ylabel='Loss')
df_acc.plot(title='Model Accuracy',figsize=(12,5)).set(xlabel='Epoch',ylabel='Accuracy')

y_pred = large_cnn_with_data_aug_model.predict(x_test)
y_pred_classes = (y_pred > 0.5).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred_classes)

# Define the class names for the binary classification
binary_class_names = [class_names[class_1_label], class_names[class_2_label]]

# Create a heatmap
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=binary_class_names, yticklabels=binary_class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

"""#### Wrong prediction Analysis"""

y_pred_prob = large_cnn_with_data_aug_model.predict(x_test)
y_pred_class = (y_pred_prob >= 0.5).astype(int)

# Find wrong predictions
wrong_idx = np.where(y_pred_class != y_test)[0]

# Get predicted probabilities for wrong predictions
wrong_pred_probs = y_pred_prob[wrong_idx]

print("Count of wrong predictions:", len(wrong_pred_probs))

print(f"min, mean and max, {np.min(wrong_pred_probs), np.mean(wrong_pred_probs), np.max(wrong_pred_probs)}")

# Define bins: 0-0.1, 0.1-0.2, ..., 0.9-1
bins = np.arange(0, 1.1, 0.1)  # 0.0, 0.1, ..., 1.0

# Compute histogram
counts, edges = np.histogram(wrong_pred_probs, bins=bins)

# Plot bar chart
plt.figure(figsize=(8,5))
bars = plt.bar(range(len(counts)), counts, tick_label=[f"{edges[i]:.1f}-{edges[i+1]:.1f}" for i in range(len(counts))], color='skyblue')

# Add count labels on top of each bar
for bar, count in zip(bars, counts):
    plt.text(bar.get_x() + bar.get_width()/2, bar.get_height(), str(count), ha='center', va='bottom')

plt.xlabel("Predicted Probability (bins)")
plt.ylabel("Count of Wrong Predictions")
plt.title("Histogram of Wrong Predictions by Predicted Probability")
plt.xticks(rotation=45)
plt.show()

# Find the indices where the true labels do not match the predicted labels
misclassified_indices = np.where(y_pred_class != y_test)[0]

# Print the number of misclassified images
print(f"Number of misclassified images: {len(misclassified_indices)}")

# Filter for high-confidence errors: probability <0.1 or >0.9
misclassified_indices = [i for i in misclassified_indices if y_pred_prob[i] < 0.05 or y_pred_prob[i] > 0.95]


# Plot a few of the misclassified images
plt.figure(figsize=(15, 10))


num_images_to_plot = min(20, len(misclassified_indices)) # Plot up to 20 misclassified images

for i in range(num_images_to_plot):
    index = misclassified_indices[i]
    plt.subplot(4, 5, i + 1) # Adjust subplot grid based on the number of images
    # Display the original image from the test set
    plt.imshow(x_test[index])
    # Display the true and predicted labels
    true_label = class_names[class_1_label] if y_test[index] == 0 else class_names[class_2_label]
    predicted_label = class_names[class_1_label] if y_pred_class[index] == 0 else class_names[class_2_label]
    plt.title(f"True: {true_label}\nPred: {predicted_label}")
    plt.axis('off')

plt.tight_layout()
plt.show()

"""### Transfer Learning With EfficientNetB0"""

from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input


# -----------------------------
# 1. Parameters
# -----------------------------
IMG_SIZE = 96
BATCH_SIZE = 32
EPOCHS_PHASE1 = 30  # training classifier head
EPOCHS_PHASE2 = 20  # fine-tuning top layers
DENSE_UNITS = 128

# -----------------------------
# 2. Resize images from 32x32 to 96x96
# -----------------------------
x_train_resized = tf.image.resize(x_train, (IMG_SIZE, IMG_SIZE)).numpy()
x_val_resized  = tf.image.resize(x_val, (IMG_SIZE, IMG_SIZE)).numpy()
x_test_resized  = tf.image.resize(x_test, (IMG_SIZE, IMG_SIZE)).numpy()

# -----------------------------
# 3. Data Augmentation for Training
# -----------------------------
train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,  # normalize to [-1,1]
    rotation_range=10,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True,
    zoom_range=0.1,
    brightness_range=[0.8, 1.2],
    shear_range=0.1,
    fill_mode='nearest',
)

val_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input  # only normalization
)

# Generators
train_gen = train_datagen.flow(
    x_train_resized, y_train,
    batch_size=BATCH_SIZE, subset='training'
)

val_gen = val_datagen.flow(
    x_val_resized, y_val,
    batch_size=BATCH_SIZE,
    shuffle=False  # keep order fixed
)

# Test generator
test_gen = val_datagen.flow(
    x_test_resized, y_test,
    batch_size=BATCH_SIZE,
    shuffle=False
)

# -----------------------------
# 4. Load Pretrained EfficientNetB0
# -----------------------------
base_model = EfficientNetB0(
    include_top=False,
    weights='imagenet',
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)
base_model.trainable = False  # freeze base initially

# Add classification head
inputs = layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = base_model(inputs, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dense(DENSE_UNITS, kernel_regularizer=regularizers.l2(1e-4))(x)
x = layers.BatchNormalization()(x)
x = layers.Activation('relu')(x)
x = layers.Dropout(0.5)(x)
outputs = layers.Dense(1, activation='sigmoid')(x)  # binary classification

model = models.Model(inputs, outputs)

# Compile model
model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-3),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

# -----------------------------
# 5. Callbacks
# -----------------------------
callbacks = [
    keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=5, verbose=1),
    keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
]

# -----------------------------
# 6. Phase 1: Train classifier head
# -----------------------------
history_phase1 = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=EPOCHS_PHASE1,
    callbacks=callbacks
)

# -----------------------------
# 7. Phase 2: Fine-tuning top layers
# -----------------------------
base_model.trainable = True
for layer in base_model.layers[:-20]:  # freeze bottom layers, fine-tune top 20
    layer.trainable = False

# Compile with lower LR for fine-tuning
model.compile(
    optimizer=optimizers.Adam(learning_rate=1e-4),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_phase2 = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=EPOCHS_PHASE2,
    callbacks=callbacks
)

# -----------------------------
# 8. Evaluate on Test Data
# -----------------------------
test_loss, test_acc = model.evaluate(test_gen)
print(f"Test Loss: {test_loss:.4f}, Test Accuracy: {test_acc:.4f}")

"""#### Model Evaluation"""

model.save('efficientnet_with_tl_weight.keras')
model.evaluate(test_gen)

# The history.history["loss"] entry is a dictionary with as many values as epochs that the
# model was trained on.
df_loss_acc = pd.DataFrame(history_phase2.history)
df_loss= df_loss_acc[['loss','val_loss']]
df_loss.rename(columns={'loss':'train','val_loss':'validation'})
df_acc= df_loss_acc[['accuracy','val_accuracy']]
df_acc.rename(columns={'accuracy':'train','val_accuracy':'validation'})
df_loss.plot(title='Model loss',figsize=(12,5)).set(xlabel='Epoch',ylabel='Loss')
df_acc.plot(title='Model Accuracy',figsize=(12,5)).set(xlabel='Epoch',ylabel='Accuracy')

y_pred = model.predict(test_gen)
y_pred_classes = (y_pred > 0.5).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred_classes)

# Define the class names for the binary classification
binary_class_names = [class_names[class_1_label], class_names[class_2_label]]

# Create a heatmap
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=binary_class_names, yticklabels=binary_class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

# Find the indices where the true labels do not match the predicted labels
misclassified_indices = np.where(y_pred_class != y_test)[0]

# Print the number of misclassified images
print(f"Number of misclassified images: {len(misclassified_indices)}")

# Filter for high-confidence errors: probability <0.1 or >0.9
misclassified_indices = [i for i in misclassified_indices if y_pred_prob[i] < 0.05 or y_pred_prob[i] > 0.95]


# Plot a few of the misclassified images
plt.figure(figsize=(6, 6))


num_images_to_plot = min(20, len(misclassified_indices)) # Plot up to 20 misclassified images

for i in range(num_images_to_plot):
    index = misclassified_indices[i]
    plt.subplot(4, 5, i + 1) # Adjust subplot grid based on the number of images
    # Display the original image from the test set
    plt.imshow(x_test[index])
    # Display the true and predicted labels
    true_label = class_names[class_1_label] if y_test[index] == 0 else class_names[class_2_label]
    predicted_label = class_names[class_1_label] if y_pred_class[index] == 0 else class_names[class_2_label]
    plt.title(f"True: {true_label}\nPred: {predicted_label}")
    plt.axis('off')

plt.tight_layout()
plt.show()

"""## Transfer learning with larger image size(from 96x96 to 128 x128)"""

import tensorflow as tf
from tensorflow.keras import layers, models, regularizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, ReduceLROnPlateau

# ===============================================
# 🧠 1. Configuration
# ===============================================
IMG_SIZE = 128            # Increase from 32 -> 128 for richer detail
BATCH_SIZE = 64
EPOCHS = 75
LR_FINE_TUNE = 1e-5
WEIGHT_DECAY = 1e-5

# ===============================================
# 🧩 2. Data preprocessing and augmentation
# ===============================================
train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,  # Normalize to [-1, 1]
    rotation_range=15,
    width_shift_range=0.15,
    height_shift_range=0.15,
    horizontal_flip=True,
    zoom_range=0.2,
    brightness_range=[0.7, 1.3],
    shear_range=0.1
)

val_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)

# Resize CIFAR-10 images
x_train_resized = tf.image.resize(x_train, (IMG_SIZE, IMG_SIZE))
x_val_resized = tf.image.resize(x_val, (IMG_SIZE, IMG_SIZE))
x_test_resized = tf.image.resize(x_test, (IMG_SIZE, IMG_SIZE))

train_gen = train_datagen.flow(x_train_resized, y_train, batch_size=BATCH_SIZE, shuffle=True)
val_gen = val_datagen.flow(x_val_resized, y_val, batch_size=BATCH_SIZE, shuffle=False)

# ===============================================
# 🏗️ 3. Build model — EfficientNetB0 backbone
# ===============================================
base_model = EfficientNetB0(
    include_top=False,
    weights='imagenet',
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)
base_model.trainable = False  # Phase 1 — freeze backbone

inputs = layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3))
x = base_model(inputs, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.4)(x)
x = layers.Dense(128, activation='relu', kernel_regularizer=regularizers.l2(1e-4))(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(1, activation='sigmoid')(x)

model = models.Model(inputs, outputs)

# ===============================================
# ⚙️ 4. Phase 1 — Train classifier head
# ===============================================
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss=tf.keras.losses.BinaryCrossentropy(label_smoothing=0.1),
    metrics=['accuracy']
)

callbacks = [
    EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    ModelCheckpoint('efficientnetb0_phase1.h5', save_best_only=True)
]

history_phase1 = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=EPOCHS,
    callbacks=callbacks
)

# ===============================================
# 🔧 5. Phase 2 — Fine-tune top layers
# ===============================================
# Unfreeze deeper portion of the model
for layer in base_model.layers[-60:]:
    layer.trainable = True

model.compile(
    optimizer=tf.keras.optimizers.AdamW(learning_rate=LR_FINE_TUNE, weight_decay=WEIGHT_DECAY),
    loss=tf.keras.losses.BinaryCrossentropy(label_smoothing=0.1),
    metrics=['accuracy']
)

callbacks_ft = [
    EarlyStopping(monitor='val_loss', patience=6, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3),
    ModelCheckpoint('efficientnetb0_finetuned.h5', save_best_only=True)
]

history_phase2 = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=EPOCHS,
    callbacks=callbacks_ft
)

# ===============================================
# 🧪 6. Evaluate
# ===============================================
test_gen = val_datagen.flow(x_test_resized, y_test, batch_size=BATCH_SIZE, shuffle=False)
test_loss, test_acc = model.evaluate(test_gen)
print(f"✅ Test accuracy: {test_acc:.4f} | Test loss: {test_loss:.4f}")

"""#### Model Evaluation"""

model.save('efficientnet_with_larger_image_tl_weight.keras')
model.evaluate(test_gen)

# The history.history["loss"] entry is a dictionary with as many values as epochs that the
# model was trained on.
df_loss_acc = pd.DataFrame(history_phase2.history)
df_loss= df_loss_acc[['loss','val_loss']]
df_loss.rename(columns={'loss':'train','val_loss':'validation'})
df_acc= df_loss_acc[['accuracy','val_accuracy']]
df_acc.rename(columns={'accuracy':'train','val_accuracy':'validation'})
df_loss.plot(title='Model loss',figsize=(12,5)).set(xlabel='Epoch',ylabel='Loss')
df_acc.plot(title='Model Accuracy',figsize=(12,5)).set(xlabel='Epoch',ylabel='Accuracy')

y_pred = model.predict(test_gen)
y_pred_classes = (y_pred > 0.5).astype(int)
conf_matrix = confusion_matrix(y_test, y_pred_classes)

# Define the class names for the binary classification
binary_class_names = [class_names[class_1_label], class_names[class_2_label]]

# Create a heatmap
plt.figure(figsize=(6, 4))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues', xticklabels=binary_class_names, yticklabels=binary_class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

# Find the indices where the true labels do not match the predicted labels
misclassified_indices = np.where(y_pred_classes != y_test)[0]

# Print the number of misclassified images
print(f"Number of misclassified images: {len(misclassified_indices)}")

# Filter for high-confidence errors: probability <0.1 or >0.9
misclassified_indices = [i for i in misclassified_indices if y_pred[i] < 0.05 or y_pred[i] > 0.95]


# Plot a few of the misclassified images
plt.figure(figsize=(10, 10))


num_images_to_plot = min(20, len(misclassified_indices)) # Plot up to 20 misclassified images

for i in range(num_images_to_plot):
    index = misclassified_indices[i]
    plt.subplot(4, 5, i + 1) # Adjust subplot grid based on the number of images
    # Display the original image from the test set
    plt.imshow(x_test[index])
    # Display the true and predicted labels
    true_label = class_names[class_1_label] if y_test[index] == 0 else class_names[class_2_label]
    predicted_label = class_names[class_1_label] if y_pred_classes[index] == 0 else class_names[class_2_label]
    plt.title(f"True: {true_label}\nPred: {predicted_label}")
    plt.axis('off')

plt.tight_layout()
plt.show()

"""## Conclusion

In this notebook, we implemented and compared several neural network models (MLP and CNN variations) for binary image classification on a subset of the CIFAR-10 dataset (distinguishing between 'cat' and 'dog' images).

The models trained were:
- MLP Model
- Basic CNN Model
- CNN with Batch Normalization and Dropout (LeNet-5 style)
- CNN with Data Augmentation (LeNet-5 style)
- Larger CNN with Data Augmentation
- Transfer Learning with EfficientNetB0

Here's a summary of the performance on the test set for each model:

| Model                                     | Train Accuracy | Test Accuracy |
|-------------------------------------------|----------------|---------------|
| MLP Model              | 98%          | 61%         |
| Basic CNN Model                           | 93%          | 73%         |
| CNN with BN and Dropout (LeNet-5 style)   | 80%          | 75%         |
| CNN with Data Augmentation (LeNet-5 style)| 80%          | 76%         |
| Larger CNN with Data Augmentation         | 99%(sign of overfitiing)          | 83%         |
| Transfer Learning with EfficientNetB0     | 92%           | 91%         |


Based on the evaluation on the test set, the **Transfer Learning with EfficientNetB0** model achieved the highest accuracy of **91**% in distinguishing between 'cat' and 'dog' images.

The confusion matrices and loss/accuracy plots for each model provide further insights into their performance and convergence during training. The analysis of misclassified images from the best performing model highlighted instances where the model struggled, often due to ambiguous or challenging visual features.

Overall, the experiments demonstrated the effectiveness of CNNs, batch normalization, data augmentation, and especially transfer learning in improving the performance of image classification models on this dataset.
"""